name: 🚀 Build & Push Docker Image

on:
  push:
    branches: [main]

env:
  PROJECT_ID: sulfikar-alijun-personal
  REGION: us-west1
  REPO: hello-devops
  IMAGE_NAME: hello-devops
  CONTAINER_NAME: hello-devops
  APP_PORT: 3000
  PUBLIC_PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repo
        uses: actions/checkout@v3

      - name: 🔧 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE_NAME:latest .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE_NAME:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE_NAME:latest
            docker run -d --name $CONTAINER_NAME -p $PUBLIC_PORT:$APP_PORT $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE_NAME:latest

